# Generated by Django 5.2.15 on 2026-07-04 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Типы занятости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус исполнителя',
                'verbose_name_plural': 'Статусы исполнителей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус подбора',
                'verbose_name_plural': 'Статусы подбора',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: АР, КР, ОВ, ВК, ЭОМ', max_length=30, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, help_text='Telegram, WhatsApp или другой способ связи', max_length=150, verbose_name='Мессенджер')),
                ('works_in_revit', models.BooleanField(default=False, verbose_name='Работает в Revit')),
                ('revit_comment', models.TextField(blank=True, help_text='Версия Revit, уровень владения, особенности работы', verbose_name='Комментарий по Revit')),
                ('status_comment', models.TextField(blank=True, help_text='Причина, почему не работаем или есть ограничения', verbose_name='Комментарий к статусу')),
                ('general_comment', models.TextField(blank=True, verbose_name='Общий комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executors', to='directory.employmenttype', verbose_name='Тип занятости')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executors', to='directory.executorstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь объекта, м²')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='directory.objecttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='directory.executor', verbose_name='Исполнитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_comments', to='directory.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Комментарий к исполнителю',
                'verbose_name_plural': 'Комментарии к исполнителям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.PositiveIntegerField(blank=True, help_text='Хранится без копеек. Например: 200000. В интерфейсе будет отображаться как 200 000.', null=True, verbose_name='Сумма КП, руб.')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_selections', to='directory.executor', verbose_name='Исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='directory.project', verbose_name='Проект')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_selections', to='directory.selectionstatus', verbose_name='Статус')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_selections', to='directory.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Подбор исполнителя',
                'verbose_name_plural': 'Подбор исполнителей',
                'ordering': ['project', 'specialty', 'executor'],
            },
        ),
        migrations.CreateModel(
            name='SelectionNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='directory.projectselection', verbose_name='Строка подбора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Переговоры по подбору',
                'verbose_name_plural': 'Переговоры по подбору',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_specialties', to='directory.executor', verbose_name='Исполнитель')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor_specialties', to='directory.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность исполнителя',
                'verbose_name_plural': 'Специальности исполнителей',
            },
        ),
        migrations.AddConstraint(
            model_name='projectselection',
            constraint=models.UniqueConstraint(fields=('project', 'specialty', 'executor'), name='unique_project_specialty_executor'),
        ),
        migrations.AddConstraint(
            model_name='executorspecialty',
            constraint=models.UniqueConstraint(fields=('executor', 'specialty'), name='unique_executor_specialty'),
        ),
    ]
