# Generated by Django 5.2.15 on 2026-07-05 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_project_chief_project_engineer_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpecialtyNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='Требуется')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_specialty_needs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_needs', to='directory.project', verbose_name='Проект')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_needs', to='directory.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Потребность проекта по разделу',
                'verbose_name_plural': 'Потребности проектов по разделам',
                'ordering': ['project__name', 'specialty__code'],
                'constraints': [models.UniqueConstraint(fields=('project', 'specialty'), name='unique_project_specialty_need')],
            },
        ),
    ]
