# Generated by Django 5.2.15 on 2026-09-04 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник контакта',
                'verbose_name_plural': 'Источники контактов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='executor',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год рождения'),
        ),
        migrations.AddField(
            model_name='executor',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город / местоположение'),
        ),
        migrations.AddField(
            model_name='executor',
            name='source_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к источнику'),
        ),
        migrations.AddField(
            model_name='executor',
            name='work_start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Начал работать с'),
        ),
        migrations.AddField(
            model_name='executor',
            name='contact_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executors', to='directory.contactsource', verbose_name='Источник контакта'),
        ),
    ]
